import { Button } from "@mantine/core"
import type { NextPage } from "next"
import Head from "next/head"
import styles from "../styles/Home.module.css"

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <div className='flex gap-3'>
          <button className='font-bold bg-blue-500 text-white py-2.3 px-3'>
            button
          </button>
          <Button>button</Button>
        </div>
      </main>
    </div>
  )
}

export default Home
